HTTP_STR_END = b"\r\n"
HTTP_END = b"\r\n\r\n"

SERVER_NAME = "SERVER 3000 XXL TURBO"

UNKNOWN = "UNKNOWN"

OK = 200
FORBIDDEN = 403
NOT_FOUND = 404
NOT_ALLOWED = 405

INDEX_PATH = "index.html"

SOCKET_PART_SIZE = 1024

STOP_TASK = "STOP_TASK"

MAX_REQUEST_SIZE = 2048